### ISSUE TITLE
Необходимость интервала, где правая граница включена в расчет ...

### ISSUE THREAD

**Issue by JohnBat26** [jmorozov/productive-kalendar#1]
Привет.
Спасибо за полезную разработку!
Вопрос: я хочу получить количество рабочих дней за, например, февраль 2019
Если я выставляю: 
```
--data '{"start": "2019-02-01","end": "2019-03-01"}'
```
То в ответ: -9

но  если я ставлю:
```
--data '{"start": "2019-02-01","end": "2019-02-28"}'
```
то получаю: 18.

А мне надо получить количество рабочих дней ВКЛЮЧИТЕЛЬНО. Можно это доработать?

**Comment by jmorozov** [comment]
Привет. Спасибо за отзыв.

Ошибку с отрицательным количеством дней исправил.

Добавил возможность указать интревал включая правую границу. Для этого надо в запросе добавить поле  `"inclusive": true`.
